#! /bin/bash
root=/gpfs51/dors2/gpc/JamesBooth/JBooth-Lab/BDL/jinwang/ReadingvOT_5_7
topnum="100" 
subjects_file_path=${root}
subjects_file=screening/final_subj_info.txt #This should be a txt file with only a list of subject numbers
contrastsname=(onset_vs_rhyme_ses-5 rhyme_vs_onset_ses-5 onset_vs_rhyme_ses-7 rhyme_vs_onset_ses-7)
contrasts=(spmT_0007.nii spmT_0008.nii spmT_0009.nii spmT_0010.nii) #This should correspond to my onset_vs_perc_ses-5, rhyme_vs_perc_ses-5, onset_vs_perc_ses7, rhyme_vs_perc_ses-7 contrast
ROIs_path=ROI
ROIs="sphere_8--36_-68_-12_mask sphere_8--46_-53_-20_mask" # you don't need to write .nii 
data_path=preproc
firstlevelspm_path=analysis_s4/deweight

########do not need to modify below############
subjects=$(grep -Eo '[0-9\.]+' ${subjects_file_path}/${subjects_file})

#do roi loop
for roi in $ROIs
do 

cd ${root}
mkdir ${roi}_topvoxels_ROIs

#do topvoxels loop
for num in $topnum
do

#do subject loop
for sub in $subjects
do

cd ${root}/${roi}_topvoxels_ROIs
mkdir sub-${sub}

#do contrast loop
for con_idx in {0..3} 
do 

cd ${root}/${roi}_topvoxels_ROIs/sub-${sub}/
# find the coordinates and the t-values within a mask 
3dmaskdump \
-mask ${root}/${ROIs_path}/${roi}.nii \
${root}/${data_path}/sub-${sub}/${firstlevelspm_path}/${contrasts[con_idx]} > ${roi}_${contrastsname[con_idx]}_output.txt

# sort the output.txt to select the top number of voxels
sort -rk4 -n ${roi}_${contrastsname[con_idx]}_output.txt | head -${num} > ${roi}_${contrastsname[con_idx]}_top${num}.txt
awk '$4+=1000' ${roi}_${contrastsname[con_idx]}_top${num}.txt > ${roi}_${contrastsname[con_idx]}_top${num}_adjust.txt

# put these top number of voxels back to brain
3dUndump \
-prefix ${roi}_${contrastsname[con_idx]}_p1_k${num}_adjust.nii \
-master ${root}/${data_path}/sub-${sub}/${firstlevelspm_path}/${contrasts[con_idx]} \
-ijk ${roi}_${contrastsname[con_idx]}_top${num}_adjust.txt
 
# make a mask of these top number of voxels (make them equal to 1)
3dcalc -a ${roi}_${contrastsname[con_idx]}_p1_k${num}_adjust.nii -expr 'ispositive(a)' -prefix ${roi}_${contrastsname[con_idx]}_p1_k${num}_adjust_mask.nii

done  # end of contrast loop

done  # end of subject loop

done  # end of num loop

done  # end of roi loop

done  # end of roi loop